### ISSUE TITLE
Sky.frag missing GLSLCompat

### ISSUE THREAD

**Issue by oxplay2** [dreamwagon/vclouds#1]
There is some issue related with my hardware i belive.

But there is simple way to fix it:

add:
#import "MatDefs/ShaderLib/GLSLCompat.glsllib"
to:
Sky.frag

GLSLCompat is intentionally in each JME shaders i belive.

**Comment by oxplay2** [comment]
well i mean:

#import "MatDefs/Common/Compat.glsllib"

because you have it copied from JME with different name.

**Comment by dreamwagon** [comment]
Fixed!
